import type { ArchitectureGraph, GraphEdge, GraphNode } from "@sdlc/contracts-ts";

/**
 * The Semantic Architecture Graph: the one source every other design artifact is
 * generated from. The domain model, the class diagram and the sequence diagrams
 * are projections over this, so renaming a node here changes all of them.
 *
 * Node kinds carry different fields on purpose: an actor has an actorKind, an
 * entity has attributes, a constraint has a standard and the
 * ids it applies to, so no constraint floats unattached.
 */
const nodes: GraphNode[] = [
  /* actors */
  {
    id: "a1",
    kind: "actor",
    label: "Customer",
    description: "Pays for things and checks what they paid for.",
    position: { x: 0, y: 120 },
    traces: ["R-1", "R-7"],
    attributes: [],
    actorKind: "primary",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a2",
    kind: "actor",
    label: "Administrator",
    description: "Reviews identity documents and reads the audit trail.",
    position: { x: 0, y: 320 },
    traces: ["R-4", "R-5"],
    attributes: [],
    actorKind: "primary",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a3",
    kind: "actor",
    label: "Payment Provider",
    description: "Stripe or PayPal, which actually moves the money.",
    position: { x: 0, y: 520 },
    traces: ["R-2", "R-8"],
    attributes: [],
    actorKind: "external_system",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a4",
    kind: "actor",
    label: "Identity Provider",
    description: "Checks submitted documents against an external register.",
    position: { x: 0, y: 700 },
    traces: ["R-3"],
    attributes: [],
    actorKind: "external_system",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  /* services */
  {
    id: "m1",
    kind: "service",
    label: "Auth Service",
    description: "Signs customers in and issues the session a payment needs.",
    position: { x: 300, y: 80 },
    traces: ["R-11"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m2",
    kind: "service",
    label: "Payment Service",
    description: "Takes a payment request, calls the provider, records the result.",
    position: { x: 300, y: 240 },
    traces: ["R-1", "R-2", "R-10"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m3",
    kind: "service",
    label: "Verification Service",
    description: "Collects identity documents and tracks their review.",
    position: { x: 300, y: 400 },
    traces: ["R-3", "R-4"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: {
      ruleId: "action-has-an-outcome",
      reason:
        "R-3 says verification happens before a large payment, but nothing says what this service does when it fails, so the outcome of a failed check is missing from the design.",
      traces: ["R-3"],
    },
    changedInVersion: null,
  },
  {
    id: "m4",
    kind: "service",
    label: "Notification Service",
    description: "Sends the customer the outcome of a payment.",
    position: { x: 300, y: 560 },
    traces: ["R-6", "R-12"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m5",
    kind: "service",
    label: "API Gateway",
    description: "One entry point, so every request is authenticated once.",
    position: { x: 560, y: 160 },
    traces: ["R-11"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m6",
    kind: "service",
    label: "Web App",
    description: "What the customer actually sees.",
    position: { x: 560, y: 360 },
    traces: ["R-1", "R-7"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  /* entities */
  {
    id: "e1",
    kind: "entity",
    label: "Customer",
    description: "A person who can pay.",
    position: { x: 860, y: 60 },
    traces: ["R-1", "R-9"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "email", type: "String" },
      { name: "displayName", type: "String" },
      { name: "verifiedAt", type: "Instant" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e2",
    kind: "entity",
    label: "Payment",
    description: "One attempt to move money, and how it ended.",
    position: { x: 860, y: 220 },
    traces: ["R-1", "R-2", "R-7"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "amount", type: "Money" },
      { name: "method", type: "PaymentMethod" },
      { name: "status", type: "PaymentStatus" },
      { name: "createdAt", type: "Instant" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e3",
    kind: "entity",
    label: "Verification",
    description: "A submitted identity document and its review outcome.",
    position: { x: 860, y: 380 },
    traces: ["R-3", "R-4"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "documentType", type: "DocumentType" },
      { name: "status", type: "VerificationStatus" },
      { name: "reviewedBy", type: "String" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: {
      ruleId: "entity-state-is-reachable",
      reason:
        "R-4 has an administrator approving documents, but no requirement says how a rejected verification is recorded, so this entity has a status no read requirement reaches.",
      traces: ["R-4"],
    },
    changedInVersion: null,
  },
  {
    id: "e4",
    kind: "entity",
    label: "Notification",
    description: "A message sent to a customer about a payment.",
    position: { x: 860, y: 540 },
    traces: ["R-6"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "channel", type: "Channel" },
      { name: "sentAt", type: "Instant" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e5",
    kind: "entity",
    label: "Audit Entry",
    description: "An append only record of something that happened.",
    position: { x: 860, y: 700 },
    traces: ["R-5"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "action", type: "String" },
      { name: "actor", type: "String" },
      { name: "at", type: "Instant" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e6",
    kind: "entity",
    label: "Session",
    description: "Proof that a customer is signed in right now.",
    position: { x: 1140, y: 140 },
    traces: ["R-11"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "expiresAt", type: "Instant" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  /* constraints, each attached to what it constrains */
  {
    id: "c1",
    kind: "constraint",
    label: "PCI DSS",
    description: "Card data never lands in the platform's own storage.",
    position: { x: 1140, y: 320 },
    traces: ["R-8"],
    attributes: [],
    actorKind: null,
    standard: "PCI DSS 4.0",
    appliesTo: ["m2", "e2"],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "c2",
    kind: "constraint",
    label: "GDPR",
    description: "Personal data can be exported and erased on request.",
    position: { x: 1140, y: 470 },
    traces: ["R-9"],
    attributes: [],
    actorKind: null,
    standard: "GDPR",
    appliesTo: ["e1", "e3", "m3"],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "c3",
    kind: "constraint",
    label: "Audit retention",
    description: "The audit trail cannot be edited after it is written.",
    position: { x: 1140, y: 620 },
    traces: ["R-5"],
    attributes: [],
    actorKind: null,
    standard: "SOC 2 Type II",
    appliesTo: ["e5"],
    unconfirmed: null,
    changedInVersion: null,
  },
];

/**
 * `action` edges are the domain sentences: actor, verb, entity. The domain
 * projection reads only these, which is why they go actor to entity directly
 * rather than through the service that happens to implement them.
 */
const edges: GraphEdge[] = [
  { id: "x1", source: "a1", target: "e2", kind: "action", verb: "makes", traces: ["R-1"] },
  { id: "x2", source: "a1", target: "e3", kind: "action", verb: "submits", traces: ["R-3"] },
  { id: "x3", source: "a1", target: "e2", kind: "action", verb: "reviews", traces: ["R-7"] },
  { id: "x4", source: "a2", target: "e3", kind: "action", verb: "approves", traces: ["R-4"] },
  { id: "x5", source: "a2", target: "e5", kind: "action", verb: "reads", traces: ["R-5"] },
  { id: "x6", source: "a3", target: "e2", kind: "action", verb: "settles", traces: ["R-2"] },
  { id: "x7", source: "a4", target: "e3", kind: "action", verb: "checks", traces: ["R-3"] },
  { id: "x8", source: "a1", target: "e6", kind: "action", verb: "opens", traces: ["R-11"] },
  { id: "x9", source: "a1", target: "e4", kind: "action", verb: "receives", traces: ["R-6"] },

  /* data: which service owns which entity */
  { id: "d1", source: "m1", target: "e6", kind: "data", verb: "creates", traces: ["R-11"] },
  { id: "d2", source: "m1", target: "e1", kind: "data", verb: "reads and writes", traces: ["R-1"] },
  { id: "d3", source: "m2", target: "e2", kind: "data", verb: "reads and writes", traces: ["R-1", "R-2"] },
  { id: "d4", source: "m3", target: "e3", kind: "data", verb: "reads and writes", traces: ["R-3"] },
  { id: "d5", source: "m4", target: "e4", kind: "data", verb: "reads and writes", traces: ["R-6"] },
  { id: "d6", source: "m2", target: "e5", kind: "data", verb: "appends to", traces: ["R-5"] },
  { id: "d7", source: "m3", target: "e5", kind: "data", verb: "appends to", traces: ["R-5"] },

  /* dependency: who calls whom */
  { id: "p1", source: "m6", target: "m5", kind: "dependency", verb: "calls", traces: ["R-1"] },
  { id: "p2", source: "m5", target: "m1", kind: "dependency", verb: "routes to", traces: ["R-11"] },
  { id: "p3", source: "m5", target: "m2", kind: "dependency", verb: "routes to", traces: ["R-1"] },
  { id: "p4", source: "m5", target: "m3", kind: "dependency", verb: "routes to", traces: ["R-3"] },
  { id: "p5", source: "m2", target: "a3", kind: "dependency", verb: "calls", traces: ["R-2"] },
  { id: "p6", source: "m3", target: "a4", kind: "dependency", verb: "calls", traces: ["R-3"] },
  { id: "p7", source: "m2", target: "m4", kind: "dependency", verb: "notifies through", traces: ["R-6", "R-12"] },
  { id: "p8", source: "m2", target: "m3", kind: "dependency", verb: "checks status with", traces: ["R-3"] },

  /* constraint: what each rule binds */
  { id: "k1", source: "c1", target: "m2", kind: "constraint", verb: "constrains", traces: ["R-8"] },
  { id: "k2", source: "c1", target: "e2", kind: "constraint", verb: "constrains", traces: ["R-8"] },
  { id: "k3", source: "c2", target: "e1", kind: "constraint", verb: "constrains", traces: ["R-9"] },
  { id: "k4", source: "c2", target: "e3", kind: "constraint", verb: "constrains", traces: ["R-9"] },
  { id: "k5", source: "c2", target: "m3", kind: "constraint", verb: "constrains", traces: ["R-9"] },
  { id: "k6", source: "c3", target: "e5", kind: "constraint", verb: "constrains", traces: ["R-5"] },
];

export const seedGraph: ArchitectureGraph = { nodes, edges, changedNodeIds: [] };
