import type { Assumption, ClarifyingQuestion, ParsedRequirement } from "@sdlc/contracts-ts";

/**
 * The parsed requirements every other artifact traces back to. Same domain the
 * app has always demoed (payments, KYC, notifications), now itemised so the
 * traceability claim is visible rather than implied.
 */
export const seedRequirements: ParsedRequirement[] = [
  {
    id: "R-1",
    text: "Customers can pay using a saved credit card or a digital wallet.",
    type: "functional",
    priority: "must",
    confidence: 96,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "The system shall allow customers to make payments using credit cards and digital wallets.",
  },
  {
    id: "R-2",
    text: "Payments are processed through Stripe and PayPal.",
    type: "functional",
    priority: "must",
    confidence: 94,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "Integrate Stripe and PayPal.",
  },
  {
    id: "R-3",
    text: "A customer completes identity verification before any payment above 1000 is processed.",
    type: "functional",
    priority: "must",
    confidence: 91,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "KYC verification is required before processing payments above $1000.",
  },
  {
    id: "R-4",
    text: "An administrator reviews and approves submitted identity documents.",
    type: "functional",
    priority: "should",
    confidence: 78,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "KYC verification is required before processing payments above $1000.",
  },
  {
    id: "R-5",
    text: "Every transaction is written to an audit trail that cannot be edited.",
    type: "functional",
    priority: "must",
    confidence: 89,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "All transactions must be audited.",
  },
  {
    id: "R-6",
    text: "Customers are notified when a payment succeeds or fails.",
    type: "functional",
    priority: "should",
    confidence: 72,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: null,
  },
  {
    id: "R-7",
    text: "Customers can see their past transactions.",
    type: "functional",
    priority: "could",
    confidence: 64,
    qualityAttribute: null,
    lowConfidence: true,
    adjusted: false,
    sourceQuote: null,
  },
  {
    id: "R-8",
    text: "Card data is never stored by the platform itself.",
    type: "constraint",
    priority: "must",
    confidence: 93,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: "The system shall allow customers to make payments using credit cards and digital wallets.",
  },
  {
    id: "R-9",
    text: "Personal data can be exported and erased on request.",
    type: "constraint",
    priority: "must",
    confidence: 81,
    qualityAttribute: null,
    lowConfidence: false,
    adjusted: false,
    sourceQuote: null,
  },
  {
    id: "R-10",
    text: "A payment is confirmed to the customer within two seconds.",
    type: "quality",
    priority: "should",
    confidence: 58,
    qualityAttribute: "performance",
    lowConfidence: true,
    adjusted: false,
    sourceQuote: null,
  },
  {
    id: "R-11",
    text: "Only an authenticated session can start a payment.",
    type: "quality",
    priority: "must",
    confidence: 88,
    qualityAttribute: "security",
    lowConfidence: false,
    adjusted: false,
    sourceQuote: null,
  },
  {
    id: "R-12",
    text: "The payment service keeps working when the notification service is down.",
    type: "quality",
    priority: "should",
    confidence: 69,
    qualityAttribute: "reliability",
    lowConfidence: false,
    adjusted: false,
    sourceQuote: null,
  },
];

/** What the analysis proceeded on where the source did not say. */
export const seedAssumptions: Assumption[] = [
  {
    id: "A-1",
    text: "Assumed the 1000 threshold is in a single currency, and that conversion is out of scope.",
    traces: ["R-3"],
    dismissed: false,
    edited: false,
  },
  {
    id: "A-2",
    text: "Assumed notifications are email and push only, with no SMS.",
    traces: ["R-6"],
    dismissed: false,
    edited: false,
  },
  {
    id: "A-3",
    text: "Assumed one administrator role, with no separate approver and auditor split.",
    traces: ["R-4", "R-5"],
    dismissed: false,
    edited: false,
  },
];

/** At most three unanswered at a time, so this never becomes a form to fill in. */
export const seedQuestions: ClarifyingQuestion[] = [
  {
    id: "Q-1",
    question: "When identity verification fails, should the payment be held or refused outright?",
    traces: ["R-3", "R-4"],
    answer: null,
    answeredAt: null,
  },
  {
    id: "Q-2",
    question: "How long does the audit trail have to be kept?",
    traces: ["R-5", "R-9"],
    answer: null,
    answeredAt: null,
  },
];
