import { describe, expect, it } from "vitest";
import { highlightCode, languageFromPath } from "./syntaxHighlight";

/**
 * Every file that was not TypeScript, Java or CSS was highlighted as TypeScript
 * and labelled so: a generated workflow's comments had "from", "as" and "The"
 * coloured as keywords, and a Dockerfile read as TypeScript.
 */
describe("which language a file is read as", () => {
  it.each([
    [".github/workflows/deploy.yml", "yaml"],
    ["render.yaml", "yaml"],
    ["vercel.json", "json"],
    ["Dockerfile", "dockerfile"],
    [".dockerignore", "plaintext"],
    ["apps/api/src/server.ts", "typescript"],
    ["apps/web/src/App.tsx", "tsx"],
    ["apps/web/index.html", "plaintext"],
  ])("%s is %s", (path, language) => {
    expect(languageFromPath(path)).toBe(language);
  });
});

describe("a YAML file's colours", () => {
  it("colours a comment as one, with no keywords inside it", () => {
    const [line] = highlightCode("# Generated by the platform from mern/deploy.yml@2.", "yaml", false);
    expect(line).toBe('<span style="color:#008000"># Generated by the platform from mern/deploy.yml@2.</span>');
  });

  it("colours a key apart from its value", () => {
    const [line] = highlightCode("  name: Deploy", "yaml", false);
    expect(line).toContain('<span style="color:#795e26">name</span>');
    expect(line).toContain('<span style="color:#24292e">Deploy</span>');
  });
});

describe("a Dockerfile's colours", () => {
  it("colours an instruction as a keyword", () => {
    const [line] = highlightCode("FROM node:22-alpine AS build", "dockerfile", false);
    expect(line.startsWith('<span style="color:#0000ff">FROM</span>')).toBe(true);
  });
});
