import type { ArchitectureGraph, GraphEdge, GraphNode } from "@sdlc/contracts-ts";

/**
 * ShopFlow's graph. Same rules as every other: each node traces to at least one
 * requirement, every constraint names what it binds, an actor is a person or
 * another system and never a screen, and no node carries a technology name.
 *
 * Laid out left to right: who uses it, what runs, what is kept.
 */
const nodes: GraphNode[] = [
  {
    id: "a1",
    kind: "actor",
    label: "Shopper",
    description: "Browses a storefront and places orders.",
    position: { x: 0, y: 140 },
    traces: ["R-1", "R-2", "R-3"],
    attributes: [],
    actorKind: "primary",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a2",
    kind: "actor",
    label: "Merchant",
    description: "Runs a storefront and manages its orders.",
    position: { x: 0, y: 320 },
    traces: ["R-5", "R-6"],
    attributes: [],
    actorKind: "primary",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a3",
    kind: "actor",
    label: "Inventory System",
    description: "The external system of record for stock levels.",
    position: { x: 0, y: 480 },
    traces: ["R-4"],
    attributes: [],
    actorKind: "external_system",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "a4",
    kind: "actor",
    label: "Payment Provider",
    description: "Takes the money for an order.",
    position: { x: 0, y: 620 },
    traces: ["R-12"],
    attributes: [],
    actorKind: "external_system",
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  {
    id: "m1",
    kind: "service",
    label: "Catalog Service",
    description: "Serves products and their categories over the API.",
    position: { x: 330, y: 60 },
    traces: ["R-1", "R-10"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m2",
    kind: "service",
    label: "Cart Service",
    description: "Holds a shopper's cart and its line items until checkout.",
    position: { x: 330, y: 210 },
    traces: ["R-2", "R-7"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m3",
    kind: "service",
    label: "Order Service",
    description: "Turns a cart into an order and tracks its status.",
    position: { x: 330, y: 360 },
    traces: ["R-3", "R-5"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "m4",
    kind: "service",
    label: "Inventory Service",
    description: "Keeps stock levels in step with the external system.",
    position: { x: 330, y: 510 },
    traces: ["R-4", "R-7"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: {
      ruleId: "sync-direction-is-stated",
      reason:
        "R-4 asks for stock to stay in step but never says which side wins when they disagree, so this service has no stated behaviour for a conflict.",
      traces: ["R-4"],
    },
    changedInVersion: null,
  },
  {
    id: "m5",
    kind: "service",
    label: "Storefront API",
    description: "The single entry point every front end calls.",
    position: { x: 330, y: 660 },
    traces: ["R-6", "R-10"],
    attributes: [],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  {
    id: "e1",
    kind: "entity",
    label: "Product",
    description: "Something a storefront sells.",
    position: { x: 720, y: 40 },
    traces: ["R-1"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "storefrontId", type: "UUID" },
      { name: "name", type: "String" },
      { name: "price", type: "Money" },
      { name: "category", type: "String" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e2",
    kind: "entity",
    label: "Cart",
    description: "What a shopper intends to buy, before they commit to it.",
    position: { x: 720, y: 200 },
    traces: ["R-2"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "storefrontId", type: "UUID" },
      { name: "lineItems", type: "LineItem[]" },
      { name: "updatedAt", type: "Timestamp" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e3",
    kind: "entity",
    label: "Order",
    description: "A committed purchase and the state it has reached.",
    position: { x: 720, y: 360 },
    traces: ["R-3", "R-5"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "storefrontId", type: "UUID" },
      { name: "status", type: "OrderStatus" },
      { name: "total", type: "Money" },
      { name: "placedAt", type: "Timestamp" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e4",
    kind: "entity",
    label: "Stock Level",
    description: "How many of a product a storefront can still sell.",
    position: { x: 720, y: 520 },
    traces: ["R-4", "R-7"],
    attributes: [
      { name: "productId", type: "UUID" },
      { name: "available", type: "Integer" },
      { name: "syncedAt", type: "Timestamp" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "e5",
    kind: "entity",
    label: "Storefront",
    description: "One merchant's shop: its catalog, branding and orders.",
    position: { x: 720, y: 670 },
    traces: ["R-6", "R-9"],
    attributes: [
      { name: "id", type: "UUID" },
      { name: "name", type: "String" },
      { name: "currency", type: "Currency" },
    ],
    actorKind: null,
    standard: null,
    appliesTo: [],
    unconfirmed: null,
    changedInVersion: null,
  },

  {
    id: "c1",
    kind: "constraint",
    label: "Tenant isolation",
    description:
      "Every read and write carries a storefront id, so one shop can never see another's data.",
    position: { x: 1080, y: 280 },
    traces: ["R-9"],
    attributes: [],
    actorKind: null,
    standard: "Tenant scoped access",
    appliesTo: ["e1", "e2", "e3", "e5", "m5"],
    unconfirmed: null,
    changedInVersion: null,
  },
  {
    id: "c2",
    kind: "constraint",
    label: "No overselling",
    description: "Checkout refuses a line item whose quantity exceeds the recorded stock level.",
    position: { x: 1080, y: 470 },
    traces: ["R-7"],
    attributes: [],
    actorKind: null,
    standard: "Stock check at checkout",
    appliesTo: ["m2", "m3", "e4"],
    unconfirmed: null,
    changedInVersion: null,
  },
];

const edges: GraphEdge[] = [
  { id: "x1", source: "a1", target: "e1", kind: "action", verb: "browses", traces: ["R-1"] },
  { id: "x2", source: "a1", target: "e2", kind: "action", verb: "fills", traces: ["R-2"] },
  { id: "x3", source: "a1", target: "e3", kind: "action", verb: "places", traces: ["R-3"] },
  { id: "x4", source: "a2", target: "e3", kind: "action", verb: "updates", traces: ["R-5"] },
  { id: "x5", source: "a2", target: "e5", kind: "action", verb: "runs", traces: ["R-6"] },
  { id: "x6", source: "a3", target: "e4", kind: "action", verb: "reports", traces: ["R-4"] },
  { id: "x7", source: "a4", target: "e3", kind: "action", verb: "settles", traces: ["R-12"] },

  { id: "d1", source: "m1", target: "e1", kind: "data", verb: "owns", traces: ["R-1"] },
  { id: "d2", source: "m2", target: "e2", kind: "data", verb: "owns", traces: ["R-2"] },
  { id: "d3", source: "m3", target: "e3", kind: "data", verb: "owns", traces: ["R-3"] },
  { id: "d4", source: "m4", target: "e4", kind: "data", verb: "owns", traces: ["R-4"] },
  { id: "d5", source: "m5", target: "e5", kind: "data", verb: "owns", traces: ["R-6"] },

  { id: "p1", source: "m5", target: "m1", kind: "dependency", verb: "calls", traces: ["R-10"] },
  { id: "p2", source: "m5", target: "m2", kind: "dependency", verb: "calls", traces: ["R-10"] },
  { id: "p3", source: "m5", target: "m3", kind: "dependency", verb: "calls", traces: ["R-10"] },
  { id: "p4", source: "m3", target: "m4", kind: "dependency", verb: "checks stock with", traces: ["R-7"] },
  { id: "p5", source: "m3", target: "a4", kind: "dependency", verb: "takes payment through", traces: ["R-12"] },
  { id: "p6", source: "m4", target: "a3", kind: "dependency", verb: "syncs from", traces: ["R-4"] },

  { id: "k1", source: "c1", target: "e1", kind: "constraint", verb: "scopes", traces: ["R-9"] },
  { id: "k2", source: "c1", target: "e3", kind: "constraint", verb: "scopes", traces: ["R-9"] },
  { id: "k3", source: "c1", target: "m5", kind: "constraint", verb: "scopes", traces: ["R-9"] },
  { id: "k4", source: "c2", target: "m3", kind: "constraint", verb: "binds", traces: ["R-7"] },
  { id: "k5", source: "c2", target: "e4", kind: "constraint", verb: "binds", traces: ["R-7"] },
];

export const seedGraph: ArchitectureGraph = { nodes, edges, changedNodeIds: [] };
