import type { ProjectDesignSeed } from "../projectSeed";

/**
 * MediTrack EHR: patient records, appointments, prescriptions and HL7 FHIR
 * interoperability, with role based access.
 *
 * Deliberately compact. Five requirements rather than twelve, one interaction,
 * two flows: the point of this snapshot is that a second project reads its own
 * brief and produces its own content, not that every project carries the same
 * volume. A compact snapshot is also the honest shape for a short brief.
 */
export const meditrackSeed: ProjectDesignSeed = {
  appName: "Records",

  requirements: [
    {
      id: "R-1",
      text: "A clinician can open a patient's record and read their history.",
      type: "functional",
      priority: "must",
      confidence: 93,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "Build an EHR system for clinics with patient records",
    },
    {
      id: "R-2",
      text: "A clinician can book, move and cancel an appointment.",
      type: "functional",
      priority: "must",
      confidence: 91,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "patient records, appointments, prescriptions",
    },
    {
      id: "R-3",
      text: "A doctor can issue a prescription against a patient's record.",
      type: "functional",
      priority: "must",
      confidence: 89,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "appointments, prescriptions",
    },
    {
      id: "R-4",
      text: "Records are exchanged with other systems as HL7 FHIR resources.",
      type: "constraint",
      priority: "must",
      confidence: 84,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "HL7 FHIR interoperability",
    },
    {
      id: "R-5",
      text: "What a user can read and write depends on whether they are a doctor, a nurse or an administrator.",
      type: "constraint",
      priority: "must",
      confidence: 86,
      qualityAttribute: "security",
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "Role-based access for doctors, nurses, and admins.",
    },
    {
      id: "R-6",
      text: "Every read of a patient record is recorded against the user who read it.",
      type: "quality",
      priority: "should",
      confidence: 47,
      qualityAttribute: "security",
      lowConfidence: true,
      adjusted: false,
      sourceQuote: null,
    },
  ],

  assumptions: [
    {
      id: "A-1",
      text: "Assumed a nurse can read a record but cannot issue a prescription, since the brief separates the roles without saying what each may do.",
      traces: ["R-3", "R-5"],
      dismissed: false,
      edited: false,
    },
    {
      id: "A-2",
      text: "Assumed FHIR R4, as the current published release.",
      traces: ["R-4"],
      dismissed: false,
      edited: false,
    },
  ],

  questions: [
    {
      id: "Q-1",
      question:
        "Does a patient record need to be readable when the FHIR exchange is unavailable, or is a read allowed to fail with it?",
      traces: ["R-1", "R-4"],
      answer: null,
      answeredAt: null,
      presetAnswer: "Readable. A clinic cannot stop working because an interface is down.",
    },
    {
      id: "Q-2",
      question: "Is the access log a regulatory requirement here, or a nice to have?",
      traces: ["R-6"],
      answer: null,
      answeredAt: null,
      presetAnswer: "Regulatory. Treat it as a must, not a should.",
    },
  ],

  nodes: [
    {
      id: "a1",
      kind: "actor",
      label: "Clinician",
      description: "A doctor or nurse using the record during care.",
      position: { x: 0, y: 120 },
      traces: ["R-1", "R-2", "R-5"],
      attributes: [],
      actorKind: "primary",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "a2",
      kind: "actor",
      label: "Administrator",
      description: "Manages users, roles and the appointment diary.",
      position: { x: 0, y: 280 },
      traces: ["R-2", "R-5"],
      attributes: [],
      actorKind: "primary",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "a3",
      kind: "actor",
      label: "FHIR Exchange",
      description: "The external system records are shared with.",
      position: { x: 0, y: 430 },
      traces: ["R-4"],
      attributes: [],
      actorKind: "external_system",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m1",
      kind: "service",
      label: "Record Service",
      description: "Reads and writes patient records.",
      position: { x: 340, y: 100 },
      traces: ["R-1", "R-3"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m2",
      kind: "service",
      label: "Scheduling Service",
      description: "Holds the appointment diary.",
      position: { x: 340, y: 260 },
      traces: ["R-2"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m3",
      kind: "service",
      label: "Interoperability Service",
      description: "Translates records to and from FHIR resources.",
      position: { x: 340, y: 420 },
      traces: ["R-4"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: {
        ruleId: "external-failure-is-handled",
        reason:
          "R-4 requires the exchange but nothing says what happens when it is unreachable, so this service has no stated behaviour for an outage. Q-1 is still asking.",
        traces: ["R-4"],
      },
      changedInVersion: null,
    },
    {
      id: "e1",
      kind: "entity",
      label: "Patient",
      description: "The person being cared for.",
      position: { x: 700, y: 60 },
      traces: ["R-1"],
      attributes: [
        { name: "id", type: "UUID" },
        { name: "name", type: "String" },
        { name: "dateOfBirth", type: "Date" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "e2",
      kind: "entity",
      label: "Appointment",
      description: "A booked slot with a clinician.",
      position: { x: 700, y: 220 },
      traces: ["R-2"],
      attributes: [
        { name: "id", type: "UUID" },
        { name: "patientId", type: "UUID" },
        { name: "startsAt", type: "Timestamp" },
        { name: "status", type: "AppointmentStatus" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "e3",
      kind: "entity",
      label: "Prescription",
      description: "A medication issued against a record.",
      position: { x: 700, y: 380 },
      traces: ["R-3"],
      attributes: [
        { name: "id", type: "UUID" },
        { name: "patientId", type: "UUID" },
        { name: "issuedBy", type: "UUID" },
        { name: "medication", type: "String" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "c1",
      kind: "constraint",
      label: "Role based access",
      description: "Every read and write is checked against the user's role before it happens.",
      position: { x: 1040, y: 180 },
      traces: ["R-5"],
      attributes: [],
      actorKind: null,
      standard: "Role based access control",
      appliesTo: ["m1", "m2", "e1", "e3"],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "c2",
      kind: "constraint",
      label: "FHIR R4",
      description: "Records leaving the system are valid FHIR R4 resources.",
      position: { x: 1040, y: 380 },
      traces: ["R-4"],
      attributes: [],
      actorKind: null,
      standard: "HL7 FHIR R4",
      appliesTo: ["m3", "e1"],
      unconfirmed: null,
      changedInVersion: null,
    },
  ],

  edges: [
    { id: "x1", source: "a1", target: "e1", kind: "action", verb: "reads", traces: ["R-1"] },
    { id: "x2", source: "a1", target: "e3", kind: "action", verb: "issues", traces: ["R-3"] },
    { id: "x3", source: "a2", target: "e2", kind: "action", verb: "books", traces: ["R-2"] },
    { id: "x4", source: "a3", target: "e1", kind: "action", verb: "exchanges", traces: ["R-4"] },
    { id: "d1", source: "m1", target: "e1", kind: "data", verb: "owns", traces: ["R-1"] },
    { id: "d2", source: "m2", target: "e2", kind: "data", verb: "owns", traces: ["R-2"] },
    { id: "d3", source: "m1", target: "e3", kind: "data", verb: "owns", traces: ["R-3"] },
    { id: "p1", source: "m3", target: "a3", kind: "dependency", verb: "exchanges with", traces: ["R-4"] },
    { id: "p2", source: "m3", target: "m1", kind: "dependency", verb: "reads from", traces: ["R-4"] },
    { id: "k1", source: "c1", target: "m1", kind: "constraint", verb: "guards", traces: ["R-5"] },
    { id: "k2", source: "c2", target: "m3", kind: "constraint", verb: "binds", traces: ["R-4"] },
  ],

  architecture: {
    candidates: [
      {
        id: "modular-monolith",
        name: "Modular Monolith",
        score: 86,
        rationale:
          "One clinic, three services in the graph, and a role check that has to hold on every read. Keeping that check in one place is worth more here than independent scaling nobody has asked for.",
        pros: [
          "The role check is enforced once, which is easier to prove to an auditor",
          "One deployment for a clinic to run",
          "A record read does not cross a network boundary",
        ],
        cons: [
          "The FHIR exchange shares capacity with clinical reads",
          "Module boundaries hold only if they are enforced in review",
        ],
      },
      {
        id: "microservices",
        name: "Microservices",
        score: 58,
        rationale:
          "The interoperability service is a genuine seam and could be deployed apart. Scheduling and records are not: they are read together on nearly every screen.",
        pros: [
          "The FHIR exchange can fail without taking records with it",
          "Interoperability can be replaced without touching records",
        ],
        cons: [
          "The role check has to be enforced in every service",
          "Records and appointments are read together, so most screens would fan out",
          "More to operate than a clinic's own team can run",
        ],
      },
    ],
    recommendedCandidateId: "modular-monolith",
    selectedCandidateId: null,
    selectedAt: null,
    selectedBy: null,
    style: {
      id: "layered",
      name: "Layered Architecture",
      note: "Applies inside whichever shape is chosen: the FHIR mapping stays in its own layer, so clinical rules do not depend on the wire format. This is a code organisation style, not a competing deployment shape, which is why it is not scored against the candidates above.",
    },
  },

  useCases: [
    {
      id: "uc-read",
      name: "Open a patient record",
      traces: ["R-1", "R-5"],
      storyId: "US-301",
      steps: [
        { fromId: "a1", toId: "m1", message: "opens a {e1}", kind: "call" },
        { fromId: "m1", toId: "m1", message: "check the role before reading", kind: "call" },
        { fromId: "m1", toId: "a1", message: "the {e1} and its history", kind: "return" },
      ],
    },
    {
      id: "uc-prescribe",
      name: "Issue a prescription",
      traces: ["R-3", "R-5"],
      storyId: "US-303",
      steps: [
        { fromId: "a1", toId: "m1", message: "issues an {e3}", kind: "call" },
        { fromId: "m1", toId: "m1", message: "only a doctor may do this", kind: "call" },
        { fromId: "m1", toId: "m3", message: "share the updated {e1}", kind: "call" },
        { fromId: "m3", toId: "a3", message: "PUT the FHIR resource", kind: "call" },
        { fromId: "m1", toId: "a1", message: "the {e3} is recorded", kind: "return" },
      ],
    },
  ],

  diagrams: [
    {
      id: "class",
      kind: "class",
      title: "Class Diagram",
      description: "The domain entities and the services that own them, generated from the graph.",
      source: null,
      useCaseId: null,
      traces: ["R-1", "R-2", "R-3"],
    },
    {
      id: "er",
      kind: "er",
      title: "Entity Relationship Diagram",
      description: "The same entities as stored data, generated from the graph.",
      source: null,
      useCaseId: null,
      traces: ["R-1", "R-3"],
    },
    {
      id: "sequence",
      kind: "sequence",
      title: "Sequence Diagram",
      description: "One interaction per use case, with names read from the graph.",
      source: null,
      useCaseId: "uc-prescribe",
      traces: ["R-3", "R-4"],
    },
  ],

  flows: [
    {
      id: "flow-record",
      name: "Patient record",
      version: "v1",
      traces: ["R-1"],
      coversStoryIds: ["US-301"],
      pendingRefinement: false,
      refinementNote: null,
      screens: [
        {
          id: "record",
          name: "Record",
          terminal: false,
          crumbs: ["Patients", "A. Okafor"],
          blocks: [
            { id: "b1", kind: "summary", label: "A. Okafor", value: "Born 1974", tone: "neutral", linkId: null },
            { id: "b2", kind: "row", label: "History", value: "14 entries", tone: "neutral", linkId: "l1" },
            { id: "b3", kind: "row", label: "Prescriptions", value: "3 active", tone: "neutral", linkId: "l1" },
          ],
          links: [{ id: "l1", label: "Open a section", targetId: "record", variant: "row" }],
        },
      ],
    },
    {
      id: "flow-appointments",
      name: "Appointments",
      version: "v1",
      traces: ["R-2"],
      coversStoryIds: ["US-302"],
      pendingRefinement: false,
      refinementNote: null,
      screens: [
        {
          id: "diary",
          name: "Diary",
          terminal: false,
          crumbs: ["Appointments"],
          blocks: [
            { id: "b1", kind: "list", label: "09:00 A. Okafor", value: "Booked", tone: "neutral", linkId: null },
            { id: "b2", kind: "list", label: "09:30 R. Patel", value: "Booked", tone: "neutral", linkId: null },
            { id: "b3", kind: "list", label: "10:00 Free", value: null, tone: "muted", linkId: "l1" },
          ],
          links: [{ id: "l1", label: "Book this slot", targetId: "diary", variant: "row" }],
        },
      ],
    },
  ],

  sprint: {
    sprintName: "Sprint 1",
    goal: "A clinician can open a record and book an appointment against it.",
    velocityAssumption: {
      points: 20,
      basis: "Assumed from a team of two over a two week sprint. No history exists yet, so this is an assumption and not a measurement.",
    },
    estimatedPoints: 18,
    proposed: [
      {
        id: "US-301",
        title: "As a clinician, I can open a patient record",
        epic: "Records",
        points: 8,
        priority: "must",
        traces: ["R-1", "R-5"],
        acceptance: [
          {
            id: "AC-301-1",
            given: "a nurse signed in to a clinic",
            when: "they open a patient in that clinic",
            then: "the record and its history are shown, and the read is logged against them",
          },
          {
            id: "AC-301-2",
            given: "a user with no role for this patient",
            when: "they request the record",
            then: "the request is refused without revealing whether the patient exists",
          },
        ],
      },
      {
        id: "US-302",
        title: "As an administrator, I can book and move appointments",
        epic: "Scheduling",
        points: 5,
        priority: "must",
        traces: ["R-2"],
        acceptance: [
          {
            id: "AC-302-1",
            given: "a free slot in the diary",
            when: "the administrator books a patient into it",
            then: "the slot shows as booked and the patient appears on the day's list",
          },
        ],
      },
      {
        id: "US-303",
        title: "As a doctor, I can issue a prescription",
        epic: "Prescribing",
        points: 5,
        priority: "must",
        traces: ["R-3", "R-5"],
        acceptance: [
          {
            id: "AC-303-1",
            given: "a doctor viewing a patient record",
            when: "they issue a prescription",
            then: "it is recorded against the patient with the doctor named",
          },
          {
            id: "AC-303-2",
            given: "a nurse viewing the same record",
            when: "they try to issue a prescription",
            then: "the action is not offered to them",
          },
        ],
      },
    ],
    backlog: [
      {
        id: "US-304",
        title: "As a clinic, records exchange as FHIR resources",
        epic: "Interoperability",
        points: 13,
        priority: "must",
        traces: ["R-4"],
        acceptance: [
          {
            id: "AC-304-1",
            given: "a patient record with a new prescription",
            when: "the exchange runs",
            then: "a valid FHIR R4 resource is sent and the response is recorded",
          },
        ],
      },
      {
        id: "US-305",
        title: "As a compliance officer, I can see who read a record",
        epic: "Audit",
        points: 5,
        priority: "should",
        traces: ["R-6"],
        acceptance: [
          {
            id: "AC-305-1",
            given: "a record read by two users today",
            when: "the officer opens its access log",
            then: "both reads are listed with who and when",
          },
        ],
      },
    ],
  },
};
