import type { ProjectDesignSeed } from "../projectSeed";

/**
 * NotifyHub: multi-channel notification orchestration with templates, delivery
 * tracking, retries and preference management.
 *
 * Compact, like MediTrack. Its interesting feature is that the actors are mostly
 * other systems: the thing that asks for a notification is a service, not a
 * person, and the graph says so rather than inventing a human to click a button.
 */
export const notifyhubSeed: ProjectDesignSeed = {
  appName: "Notifications",

  requirements: [
    {
      id: "R-1",
      text: "A calling system can request a notification and have it delivered by email, SMS or push.",
      type: "functional",
      priority: "must",
      confidence: 94,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "Design a notification service supporting email, SMS, and push.",
    },
    {
      id: "R-2",
      text: "A notification's wording comes from a named template with values filled in.",
      type: "functional",
      priority: "must",
      confidence: 90,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "Include templates, delivery tracking, retries",
    },
    {
      id: "R-3",
      text: "The outcome of every delivery attempt is recorded and can be looked up.",
      type: "functional",
      priority: "must",
      confidence: 88,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "templates, delivery tracking, retries",
    },
    {
      id: "R-4",
      text: "A failed delivery is retried, and stops being retried once it succeeds or runs out of attempts.",
      type: "functional",
      priority: "must",
      confidence: 66,
      qualityAttribute: null,
      lowConfidence: true,
      adjusted: false,
      sourceQuote: "delivery tracking, retries, and preference management",
    },
    {
      id: "R-5",
      text: "A recipient can say which channels they will accept, and that choice is honoured.",
      type: "functional",
      priority: "must",
      confidence: 85,
      qualityAttribute: null,
      lowConfidence: false,
      adjusted: false,
      sourceQuote: "and preference management",
    },
    {
      id: "R-6",
      text: "A recipient is never sent the same notification twice because of a retry.",
      type: "constraint",
      priority: "must",
      confidence: 52,
      qualityAttribute: "reliability",
      lowConfidence: true,
      adjusted: false,
      sourceQuote: null,
    },
  ],

  assumptions: [
    {
      id: "A-1",
      text: "Assumed a fixed retry ceiling with a growing delay between attempts, since the brief asks for retries without saying how many.",
      traces: ["R-4"],
      dismissed: false,
      edited: false,
    },
    {
      id: "A-2",
      text: "Assumed a recipient opting out of a channel blocks even urgent notifications on it, with no override.",
      traces: ["R-5"],
      dismissed: false,
      edited: false,
    },
  ],

  questions: [
    {
      id: "Q-1",
      question:
        "When a recipient has opted out of every channel a notification could use, should it be dropped or held?",
      traces: ["R-1", "R-5"],
      answer: null,
      answeredAt: null,
      presetAnswer: "Drop it, and record that it was dropped and why.",
    },
    {
      id: "Q-2",
      question: "How many retry attempts before a delivery is abandoned?",
      traces: ["R-4"],
      answer: null,
      answeredAt: null,
      presetAnswer: "Five, with the delay doubling each time.",
    },
  ],

  nodes: [
    {
      id: "a1",
      kind: "actor",
      label: "Calling System",
      description: "Any service that asks for a notification to be sent.",
      position: { x: 0, y: 120 },
      traces: ["R-1"],
      attributes: [],
      actorKind: "external_system",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "a2",
      kind: "actor",
      label: "Recipient",
      description: "The person a notification is delivered to.",
      position: { x: 0, y: 280 },
      traces: ["R-5"],
      attributes: [],
      actorKind: "primary",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "a3",
      kind: "actor",
      label: "Channel Provider",
      description: "The external email, SMS or push service that does the delivering.",
      position: { x: 0, y: 430 },
      traces: ["R-1", "R-3"],
      attributes: [],
      actorKind: "external_system",
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m1",
      kind: "service",
      label: "Dispatch Service",
      description: "Decides which channels a notification may use and hands it to them.",
      position: { x: 340, y: 120 },
      traces: ["R-1", "R-5"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m2",
      kind: "service",
      label: "Template Service",
      description: "Renders a named template with the values supplied.",
      position: { x: 340, y: 280 },
      traces: ["R-2"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "m3",
      kind: "service",
      label: "Retry Service",
      description: "Attempts a failed delivery again until it succeeds or runs out.",
      position: { x: 340, y: 440 },
      traces: ["R-4", "R-6"],
      attributes: [],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: {
        ruleId: "retry-is-bounded",
        reason:
          "R-4 asks for retries and R-6 forbids a duplicate, but no requirement states an attempt ceiling, so nothing here says when this service stops. Q-2 is still asking.",
        traces: ["R-4", "R-6"],
      },
      changedInVersion: null,
    },
    {
      id: "e1",
      kind: "entity",
      label: "Notification",
      description: "One request to tell somebody something.",
      position: { x: 700, y: 80 },
      traces: ["R-1", "R-2"],
      attributes: [
        { name: "id", type: "UUID" },
        { name: "templateId", type: "String" },
        { name: "recipientId", type: "UUID" },
        { name: "createdAt", type: "Timestamp" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "e2",
      kind: "entity",
      label: "Delivery Attempt",
      description: "One try on one channel, and how it went.",
      position: { x: 700, y: 250 },
      traces: ["R-3", "R-4"],
      attributes: [
        { name: "id", type: "UUID" },
        { name: "notificationId", type: "UUID" },
        { name: "channel", type: "Channel" },
        { name: "outcome", type: "DeliveryOutcome" },
        { name: "attemptedAt", type: "Timestamp" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "e3",
      kind: "entity",
      label: "Channel Preference",
      description: "Which channels a recipient will accept.",
      position: { x: 700, y: 420 },
      traces: ["R-5"],
      attributes: [
        { name: "recipientId", type: "UUID" },
        { name: "channel", type: "Channel" },
        { name: "accepted", type: "Boolean" },
      ],
      actorKind: null,
      standard: null,
      appliesTo: [],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "c1",
      kind: "constraint",
      label: "Preferences are honoured",
      description: "A channel the recipient has declined is never attempted.",
      position: { x: 1040, y: 200 },
      traces: ["R-5"],
      attributes: [],
      actorKind: null,
      standard: "Recipient consent",
      appliesTo: ["m1", "e3"],
      unconfirmed: null,
      changedInVersion: null,
    },
    {
      id: "c2",
      kind: "constraint",
      label: "Delivered at most once",
      description: "A retry never produces a second delivery of a notification that already arrived.",
      position: { x: 1040, y: 390 },
      traces: ["R-6"],
      attributes: [],
      actorKind: null,
      standard: "At most once delivery",
      appliesTo: ["m3", "e2"],
      unconfirmed: null,
      changedInVersion: null,
    },
  ],

  edges: [
    { id: "x1", source: "a1", target: "e1", kind: "action", verb: "requests", traces: ["R-1"] },
    { id: "x2", source: "a2", target: "e3", kind: "action", verb: "sets", traces: ["R-5"] },
    { id: "x3", source: "a3", target: "e2", kind: "action", verb: "reports", traces: ["R-3"] },
    { id: "d1", source: "m1", target: "e1", kind: "data", verb: "owns", traces: ["R-1"] },
    { id: "d2", source: "m3", target: "e2", kind: "data", verb: "owns", traces: ["R-4"] },
    { id: "d3", source: "m1", target: "e3", kind: "data", verb: "reads", traces: ["R-5"] },
    { id: "p1", source: "m1", target: "m2", kind: "dependency", verb: "renders with", traces: ["R-2"] },
    { id: "p2", source: "m1", target: "a3", kind: "dependency", verb: "delivers through", traces: ["R-1"] },
    { id: "p3", source: "m3", target: "m1", kind: "dependency", verb: "asks again through", traces: ["R-4"] },
    { id: "k1", source: "c1", target: "m1", kind: "constraint", verb: "binds", traces: ["R-5"] },
    { id: "k2", source: "c2", target: "m3", kind: "constraint", verb: "binds", traces: ["R-6"] },
  ],

  architecture: {
    candidates: [
      {
        id: "queue-worker",
        name: "Queue and workers",
        score: 89,
        rationale:
          "Every requirement here is asynchronous: a request arrives, an attempt is made later, a failure is tried again after a delay. A durable queue with workers is the shape that survives a provider outage without losing a notification.",
        pros: [
          "A provider outage delays delivery instead of losing it",
          "Retries with a growing delay are what a queue already does",
          "Request handling scales apart from delivery",
        ],
        cons: [
          "A broker to run and watch, which nothing else here needs",
          "At most once delivery needs an idempotency key, not just a queue",
        ],
      },
      {
        id: "modular-monolith",
        name: "Modular Monolith",
        score: 62,
        rationale:
          "One deployment, and dispatch, templates and retries in one place. The cost is that a slow provider holds the request thread, which is exactly the failure this service exists to absorb.",
        pros: [
          "One deployment to run and roll back",
          "No broker to operate",
        ],
        cons: [
          "A slow provider blocks the caller, which R-1 implies it should not",
          "Retries need their own scheduler anyway, so the simplicity is partly illusory",
        ],
      },
    ],
    recommendedCandidateId: "queue-worker",
    selectedCandidateId: null,
    selectedAt: null,
    selectedBy: null,
    style: {
      id: "hexagonal",
      name: "Hexagonal Architecture",
      note: "Applies inside whichever shape is chosen: each channel provider sits behind a port, so adding a fourth channel does not touch dispatch logic. This is a code organisation style, not a competing deployment shape, which is why it is not scored against the candidates above.",
    },
  },

  useCases: [
    {
      id: "uc-send",
      name: "Send a notification",
      traces: ["R-1", "R-2", "R-5"],
      storyId: "US-401",
      steps: [
        { fromId: "a1", toId: "m1", message: "requests a {e1}", kind: "call" },
        { fromId: "m1", toId: "e3", message: "which channels will this {a2} accept", kind: "call" },
        { fromId: "m1", toId: "m2", message: "render the template", kind: "call" },
        { fromId: "m2", toId: "m1", message: "the wording", kind: "return" },
        { fromId: "m1", toId: "a3", message: "deliver it", kind: "call" },
        { fromId: "a3", toId: "m1", message: "accepted for delivery", kind: "return" },
        { fromId: "m1", toId: "a1", message: "the {e1} id", kind: "return" },
      ],
    },
    {
      id: "uc-retry",
      name: "Retry a failed delivery",
      traces: ["R-3", "R-4", "R-6"],
      storyId: "US-403",
      steps: [
        { fromId: "a3", toId: "m3", message: "reports a failed {e2}", kind: "call" },
        { fromId: "m3", toId: "m3", message: "has this {e1} already arrived", kind: "call" },
        { fromId: "m3", toId: "m1", message: "try it again after a delay", kind: "call" },
        { fromId: "m3", toId: "m3", message: "the attempt ceiling is not yet decided", kind: "note" },
      ],
    },
  ],

  diagrams: [
    {
      id: "class",
      kind: "class",
      title: "Class Diagram",
      description: "The domain entities and the services that own them, generated from the graph.",
      source: null,
      useCaseId: null,
      traces: ["R-1", "R-3", "R-5"],
    },
    {
      id: "er",
      kind: "er",
      title: "Entity Relationship Diagram",
      description: "The same entities as stored data, generated from the graph.",
      source: null,
      useCaseId: null,
      traces: ["R-1", "R-3"],
    },
    {
      id: "activity",
      kind: "activity",
      title: "Activity Diagram",
      description: "What happens to one notification, including the retry loop.",
      source: `flowchart TD
  A([Notification requested]) --> B{Any accepted channel}
  B -- no --> B1[Record it as dropped] --> Z([Nothing sent])
  B -- yes --> C[Render the template]
  C --> D[Hand it to the provider]
  D --> E{Provider accepted}
  E -- yes --> F([Delivered])
  E -- no --> G{Attempts left}
  G -- yes --> H[Wait, then try again] --> D
  G -- no --> I([Abandoned and recorded])`,
      useCaseId: null,
      traces: ["R-1", "R-4", "R-5"],
    },
    {
      id: "sequence",
      kind: "sequence",
      title: "Sequence Diagram",
      description: "One interaction per use case, with names read from the graph.",
      source: null,
      useCaseId: "uc-send",
      traces: ["R-1", "R-2"],
    },
  ],

  flows: [
    {
      id: "flow-preferences",
      name: "Channel preferences",
      version: "v1",
      traces: ["R-5"],
      coversStoryIds: ["US-402"],
      pendingRefinement: false,
      refinementNote: null,
      screens: [
        {
          id: "preferences",
          name: "Preferences",
          terminal: false,
          crumbs: ["Preferences"],
          blocks: [
            { id: "b1", kind: "row", label: "Email", value: "On", tone: "positive", linkId: "l1" },
            { id: "b2", kind: "row", label: "SMS", value: "Off", tone: "muted", linkId: "l1" },
            { id: "b3", kind: "row", label: "Push", value: "On", tone: "positive", linkId: "l1" },
          ],
          links: [{ id: "l1", label: "Toggle a channel", targetId: "preferences", variant: "row" }],
        },
      ],
    },
    {
      id: "flow-delivery-log",
      name: "Delivery log",
      version: "v1",
      traces: ["R-3"],
      coversStoryIds: ["US-404"],
      pendingRefinement: false,
      refinementNote: null,
      screens: [
        {
          id: "log",
          name: "Delivery log",
          terminal: false,
          crumbs: ["Deliveries"],
          blocks: [
            { id: "b1", kind: "list", label: "Order shipped, email", value: "Delivered", tone: "positive", linkId: null },
            { id: "b2", kind: "list", label: "Order shipped, SMS", value: "Declined by preference", tone: "muted", linkId: null },
            { id: "b3", kind: "list", label: "Password reset, email", value: "Failed, retrying", tone: "neutral", linkId: null },
          ],
          links: [{ id: "l1", label: "Open an attempt", targetId: "log", variant: "row" }],
        },
      ],
    },
  ],

  sprint: {
    sprintName: "Sprint 1",
    goal: "A calling system can ask for a notification and see what happened to it.",
    velocityAssumption: {
      points: 22,
      basis: "Assumed from a team of two over a two week sprint. No history exists yet, so this is an assumption and not a measurement.",
    },
    estimatedPoints: 21,
    proposed: [
      {
        id: "US-401",
        title: "As a calling system, I can request a notification on any channel",
        epic: "Dispatch",
        points: 8,
        priority: "must",
        traces: ["R-1", "R-2"],
        acceptance: [
          {
            id: "AC-401-1",
            given: "a recipient accepting email",
            when: "a system requests a notification from a named template",
            then: "the rendered message is handed to the email provider and an attempt is recorded",
          },
          {
            id: "AC-401-2",
            given: "a template name that does not exist",
            when: "a system requests a notification with it",
            then: "the request is refused naming the template, and nothing is queued",
          },
        ],
      },
      {
        id: "US-402",
        title: "As a recipient, I can choose which channels reach me",
        epic: "Preferences",
        points: 5,
        priority: "must",
        traces: ["R-5"],
        acceptance: [
          {
            id: "AC-402-1",
            given: "a recipient who has turned SMS off",
            when: "a notification that could use SMS is requested",
            then: "no SMS is attempted and the reason is recorded against the notification",
          },
        ],
      },
      {
        id: "US-403",
        title: "As an operator, a failed delivery is retried without duplicating it",
        epic: "Reliability",
        points: 8,
        priority: "must",
        traces: ["R-4", "R-6"],
        acceptance: [
          {
            id: "AC-403-1",
            given: "a delivery the provider rejected once",
            when: "the retry runs",
            then: "a second attempt is recorded and the recipient receives the message once",
          },
          {
            id: "AC-403-2",
            given: "a delivery that already succeeded",
            when: "a late failure report arrives for it",
            then: "no further attempt is made",
          },
        ],
      },
    ],
    backlog: [
      {
        id: "US-404",
        title: "As an operator, I can look up what happened to a notification",
        epic: "Tracking",
        points: 5,
        priority: "must",
        traces: ["R-3"],
        acceptance: [
          {
            id: "AC-404-1",
            given: "a notification with two attempts",
            when: "the operator opens it",
            then: "both attempts are listed with channel, outcome and time",
          },
        ],
      },
    ],
  },
};
